from app.extensions import db
import datetime


class User(db.Model):
    """
    Database table to store users.
    """

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.String(255), unique=True, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False)

    def __init__(
        self,
        user_id: str,
        created_at: datetime.datetime = datetime.datetime.now().isoformat(),
    ):
        """
        Initialize the User object.
        """
        self.user_id = user_id
        self.created_at = created_at

    def __repr__(self):
        """
        Return a string representation of the User object.
        """
        return f"<User user_id={self.user_id} created_at={self.created_at}>"


class Action(db.Model):
    """
    Database table to store action generated by the RL algorithm.
    """

    __tablename__ = "actions"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.String(255), nullable=False)
    state = db.Column(db.JSON, nullable=True)
    raw_context = db.Column(db.JSON, nullable=True)
    action = db.Column(db.Integer, nullable=False)
    action_prob = db.Column(db.Float, nullable=False)
    random_state = db.Column(db.JSON, nullable=False)
    request_timestamp = db.Column(db.DateTime, nullable=False)
    timestamp = db.Column(db.DateTime, nullable=False)

    def __init__(
        self,
        user_id: str,
        action: int,
        state: dict,
        raw_context: dict,
        action_prob: float,
        random_state: dict,
        request_timestamp: datetime.datetime,
        timestamp: datetime.datetime = datetime.datetime.now().isoformat(),
    ):
        """
        Initialize the Action object.
        """
        self.user_id = user_id
        self.action = action
        self.state = state
        self.raw_context = raw_context
        self.action_prob = action_prob
        self.random_state = random_state
        self.request_timestamp = request_timestamp
        self.timestamp = timestamp

    def __repr__(self):
        """
        Return a string representation of the Action object.
        """
        return f"<Action user_id={self.user_id}, action={self.action}, state={self.state}, action_prob={self.action_prob}>"


class ModelParameters(db.Model):
    """
    Database table to store parameters for the decision making algorithm.
    This example assumes a fixed probability algorithm, so the parameters are
    nothing but the probability of taking an action.
    """

    __tablename__ = "model_parameters"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    probability_of_action = db.Column(db.Float, nullable=False)
    timestamp = db.Column(db.DateTime, nullable=False)

    def __init__(
        self,
        probability_of_action: float,
        timestamp: datetime.datetime = datetime.datetime.now().isoformat(),
    ):
        """
        Initialize the ModelParameters object.
        """
        self.probability_of_action = probability_of_action
        self.timestamp = timestamp

    def __repr__(self):
        """
        Return a string representation of the ModelParameters object.
        """
        return f"<ModelParameters probability_of_action={self.probability_of_action}>"

class ModelUpdateRequests(db.Model):
    """
    Database table to store model update requests.
    """

    __tablename__ = "model_update_requests"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    update_id = db.Column(db.String(255), nullable=False)
    status = db.Column(db.String(50), nullable=False, default="processing")
    callback_url = db.Column(db.String(1024), nullable=False)
    created_at = db.Column(db.DateTime, nullable=False)
    completed_at = db.Column(db.DateTime, nullable=True)
    error_message = db.Column(db.String(1024), nullable=True)

    def __init__(
        self,
        update_id: str,
        callback_url: str,
        created_at: datetime.datetime = datetime.datetime.now().isoformat(),
    ):
        """
        Initialize the ModelUpdateRequests object.
        """
        self.update_id = update_id
        self.callback_url = callback_url
        self.created_at = created_at
    
    def __repr__(self):
        """
        Return a string representation of the ModelUpdateRequests object.
        """
        return f"<ModelUpdateRequests update_id={self.update_id}, status={self.status}>"


class StudyData(db.Model):
    """
    Database table to store study data.
    """

    __tablename__ = "study_data"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.String(255), nullable=False)
    action = db.Column(db.Integer, nullable=False)
    context = db.Column(db.JSON, nullable=False)
    decision_time = db.Column(db.Integer, nullable=False)
    timestamp = db.Column(db.DateTime, default=db.func.now())

    def __repr__(self):
        return f"<StudyData user_id={self.user_id}, study_data={self.study_data}>"
